Tidy up comments

diff --git a/templates/bash b/templates/bash
--- a/templates/bash
+++ b/templates/bash
@@ -3,21 +3,46 @@
 # Description of script
 
 # Set colours
-NC='\033[0m'
+NC='\033[0m'  # No colour
 RED='\033[0;31m'
 GREEN='\033[1;32m'
 YELLOW='\033[1;33m'
 
+NOW=$(date +'%Y-%m-%d %H:%M:%S')
+
 # Helpers
-error() {
-  printf "${RED}ERROR ${NC}- $*\n" >&2
+info () {
+  # shellcheck disable=SC2059  # for clarity instead of format specifiers
+  printf "[$NOW]: INFO - $*\n"
 }
 
-usage() {
-
+warn () {
+  # shellcheck disable=SC2059  # for clarity instead of format specifiers
+  printf "[$NOW]: ${YELLOW}WARNING ${NC}- $*\n"
 }
 
+error () {
+  # shellcheck disable=SC2059  # for clarity instead of format specifiers
+  printf "[$NOW]: ${RED}ERROR ${NC}- $*\n" >&2
+}
 
-if test; then
-  # do something
+usage () {
+  local script_name
+  script_name=$(basename "$0")
+  cat <<EOF
+Script to do something.
+
+Usage: $script_name [ -s | -h | -v ] [ command name ] [ command option ]
+
+    -s | --short   Short output
+    -v | --version Show version
+    -h | --help    Help
+
+EOF
+} 
+
+# Main #########################################################################
+
+if :; then
+  echo -e "${GREEN}Success${NC}"
 fi
